### ISSUE TITLE
Request - Exports and HUD disable in config

### ISSUE THREAD

**Issue by FaisalAlY** [VORPCORE/VORP-Metabolism#1]
Can you add an option to disable the hud design and the control of radar by the script and also function exports to food and thirst to use external hud design please?

**Comment by Artzalez** [comment]
> Can you add an option to disable the hud design and the control of radar by the script and also function exports to food and thirst to use external hud design please?

http://docs.vorpcore.com:3000/vorp-metabolism don't need exports you can use this
And for disable hud i think can update with config option (added to features)
