### ISSUE TITLE
Metabolism Script Errors When Using a Consumable Item

### ISSUE THREAD

**Issue by Cimaxion** [VORPCORE/VORP-Metabolism#9]
Hi. When my server starts it loads metabolism without any errors. However, when I use a consumable like 'consumable_kidneybeans_can', the server reports a group of script errors.

These are the errors:

[script:vorp_metaboli] Error invoking callback for event vorpmetabolism:GetStatus: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
[script:vorp_metaboli]   at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,object,int)
[script:vorp_metaboli]   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1) [0x0011d] in <cf8f429092f345a6bd742c3476e00e06>:0
[script:vorp_metaboli]   at vorpmetabolism_sv.vorpmetabolism_init.GetLastStatus (CitizenFX.Core.Player player) [0x000b6] in <888be3ae7ad9451d8020d2cabdb989f0>:0
[script:vorp_metaboli]   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
[script:vorp_metaboli]   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <fbc4ec45371543bfba3678ebb82caf6d>:0
[script:vorp_metaboli]    Exception_EndOfInnerExceptionStack
[script:vorp_metaboli]   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <fbc4ec45371543bfba3678ebb82caf6d>:0
[script:vorp_metaboli]   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <fbc4ec45371543bfba3678ebb82caf6d>:0
[script:vorp_metaboli]   at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e7] in <fbc4ec45371543bfba3678ebb82caf6d>:0
[script:vorp_metaboli]   at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in <fbc4ec45371543bfba3678ebb82caf6d>:0
[script:vorp_metaboli]   at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <fbc4ec45371543bfba3678ebb82caf6d>:0
[script:vorp_metaboli]   at CitizenFX.Core.EventHandlerEntry.Invoke (System.String sourceString, System.Object[] args) [0x00064] in C:\gl\builds\4ff63adb\0\cfx\fivem\code\client\clrcore\EventHandlerDictionary.cs:107

**Comment by eltison** [comment]
same error here

`[   1519672] [b1436_GTAProce]             MainThrd/   at CitizenFX.Core.EventHandlerEntry+<Invoke>d__5.MoveNext () [0x00064] in C:\gl\builds\master\fivem\code\client\clrcore\EventHandlerDictionary.cs:107`

**Comment by outsider31000** [comment]
use whats in premade
